version: '3.7'
services:
  annov_db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-annov4}
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-user}
    ports:
      - "5435:5432"
    env_file: ".env"
  app:
    image: annov4/spring_crud_annov4:latest
    ports:
      - "8080:8080"
    env_file: ".env"
    depends_on:
      - annov_db
    environment:
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_KEY=${ACCESS_KEY}
volumes:
  pg_annov: