version: '3.7'
services:
  annov_db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-annov4}
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-user}
    ports:
      - "5432:5432"
    env_file: "file.env"
  app:
    image: annov4/spring_crud_annov4:latest
    ports:
      - "8080:8080"
    env_file: "file.env"
    depends_on:
      - annov_db
    environment:
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - API_KEY=cb7093256c8ed475de23fb01148b5f690f3206a7
      - SECRET_KEY=47ed84c5594a87a7ba53a7edb3bff33022d66516
      - ACCESS_KEY=3cf5af7e-da4a-403d-8864-b452374ec1bc
volumes:
  pg_annov: