version: '3.7'
services:
  annov_db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg_annov:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: "file.env"
  app:
    image: annov4/spring_crud_annov4
    ports:
      - "8080:8080"
    env_file: "file.env"
    depends_on:
      - annov_db
    environment:
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

volumes:
  pg_annov: