version: '3.7'
services:
  annov_db:
    image: postgres
    container_name: annov4-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg_annov:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: "file.env"
  app:
    image: annov4/spring_crud_app:amd64
    container_name: annov4-app
    ports:
      - "8080:8080"
    env_file: "file.env"
    depends_on:
      - annov_db
    environment:
      - DATASOURCE_USERNAME=${DB_USER}
      - DATASOURCE_PASSWORD=${DB_PASSWORD}
      - DATASOURCE_URL=${DATASOURCE_URL}
volumes:
  pg_annov:

