spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: create-drop
          open-in-view: false