spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://annov_db:5432/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: none
          open-in-view: false

roles:
  admin: ROLE_ADMIN
  user: ROLE_USER