spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/annov4
    username: user
    password: 377226535
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: none
          open-in-view: false
roles:
  admin: ROLE_ADMIN
  user: ROLE_USER
weather:
  api-key: ${API_KEY}
  secret-key: ${SECRET_KEY}
  access-key: ${ACCESS_KEY}