name: Build & Deploy

on:
    push:
      branches:
        - main
push_docker_compose:
  name: Push docker-compose.yml to remote server
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

    - name: Copy docker-compose.yml to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "docker-compose.yml"
        target: "/home/${{ secrets.REMOTE_USER }}/"

    - name: Copy file.env to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "file.env"
        target: "/home/${{ secrets.REMOTE_USER }}/"
jobs:
    build_and_push_images:
      name: Build and Push image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Push to Dockerhub
          uses: docker/build-push-action@v2
          with:
            file: ./Dockerfile
            push: true
            tags: annov4/spring_crud_annov4:amd64
