name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_push_images:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: annov4/spring_crud_annov4:latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build_and_push_images]
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.REMOTE_USER }}/test/Spring_Crud_security2.0/
            echo DB_USER=${{ secrets.DB_USER }} >> .env
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            
            sudo -S docker stop spring_crud_security20_app_1
            sudo -S docker rm spring_crud_security20_app_1
            sudo -S docker rmi annov4/spring_crud_annov4:latest
            sudo docker-compose down
            sudo docker-compose -f /home/${{ secrets.REMOTE_USER }}/test/Spring_Crud_security2.0/docker-compose.yml pull
            sudo docker-compose -f /home/${{ secrets.REMOTE_USER }}/test/Spring_Crud_security2.0/docker-compose.yml up -d --remove-orphans
            sudo -S docker-compose up --force-recreate -d