name: Build & Deploy
on:
  push:
    branches:
      - main

jobs:
  push_compose:
    name: Push docker_compose.yml to remote server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/${{ secrets.REMOTE_USER }}/crud/"

  build_and_push_images:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true

          no-cache: true

          tags: annov4/spring_crud_annov4:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build_and_push_images, push_compose]
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{secrets.REMOTE_USER}}/pick_up/
            echo DB_USER=${{ secrets.DB_USER }} >> .env
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            
            sudo -S docker stop crud_app_1
            sudo -S docker rm crud_app_1
            sudo -S docker rmi annov4/spring_crud_annov4:latest
            
            sudo -S docker-compose up --force-recreate -d
            
            sudo -S docker ps -a